In [1]:
import numpy as np

import time
lst = list(range(10000000))
arr = np.arange(1000000)

start = time.time()
sum(lst)
print("list time:", time.time() - start)

start = time.time()
np.sum(arr)
print("Numpy time:", time.time() - start)


list time: 0.140106201171875
Numpy time: 0.0012412071228027344


In [2]:
# creating Arrays

In [3]:
# 1D Array

In [4]:
arr1 = np.array([1,2,3,4])
print("1D Array:", arr1)

1D Array: [1 2 3 4]


In [5]:
# 2D Array

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
ones = np.ones((3, 3))
print("ones:\n", ones)

ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
range_array =np.arange(0, 10, 2)
print("Range array:", range_array)

Range array: [0 2 4 6 8]


In [9]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([10, 20, 30])

print("Addition:", arr_a + arr_b)
print("Multipliction:", arr_a * arr_b)
print("Squared:", arr_a ** 2)

Addition: [11 22 33]
Multipliction: [10 40 90]
Squared: [1 4 9]


In [10]:
# Broadcasting
matrix = np.array([[1, 2], [3, 4]])

print("original matrix\n", matrix)
print()
print("Add scalar 5:\n", matrix + 5)

original matrix
 [[1 2]
 [3 4]]

Add scalar 5:
 [[6 7]
 [8 9]]


In [11]:
# Indexing, slicing, rashaping

In [12]:
arr = np.array([[10,20,30], [40, 50, 60]])
print("original array:\n", arr)
print()
# indexing
print("Element [0, 1]:", arr[0, 1])

original array:
 [[10 20 30]
 [40 50 60]]

Element [0, 1]: 20


In [13]:
# slicing
print("First row:", arr[0,:])

First row: [10 20 30]


In [14]:
print("last colom:", arr[:, -1])

last colom: [30 60]


In [15]:
# Reshaping
reshaped = np.arange(12).reshaped(4, 3)
print("Reshaped (3*4):\n\n", reshaped)

AttributeError: 'numpy.ndarray' object has no attribute 'reshaped'

In [ ]:
# useful numpy function

In [ ]:
arr = np.array([4,7,2,18,3])
print("mean:", np.mean(arr))

In [ ]:
print("standard diviation:", np.std(arr))

In [ ]:
print("sorted:", np.sort(arr))

In [16]:
mat = np.arange(1, 26).reshape(5, 5)
print("5*5 matrix", mat)

5*5 matrix [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:

# case study: customer feedback analiysis in reail industry using numpy


In [18]:
data = np.array([
    ["c001", 5, "Excellent service and friendly staff"],
    ["c002", 3, "Excellent service and friendly staff"],
    ["c003", 4, "Excellent service and friendly staff"],
    ["c004", 6, "Excellent service and friendly staff"],
    ["c005", 7, "Excellent service and friendly staff"],
    ["c006", 8, "Excellent service and friendly staff"],
    ["c007", 9, "Excellent service and friendly staff"],
])

In [19]:
print(data)

[['c001' '5' 'Excellent service and friendly staff']
 ['c002' '3' 'Excellent service and friendly staff']
 ['c003' '4' 'Excellent service and friendly staff']
 ['c004' '6' 'Excellent service and friendly staff']
 ['c005' '7' 'Excellent service and friendly staff']
 ['c006' '8' 'Excellent service and friendly staff']
 ['c007' '9' 'Excellent service and friendly staff']]


In [20]:
# step 2: extract numerical ratingsfor analysis
ratings = data[:, 1].astype(int) #convert rating column to integers
print(f"Total Feedback Entries: {len(ratings)}")

Total Feedback Entries: 7


In [21]:
ratings

array([5, 3, 4, 6, 7, 8, 9])

In [22]:
# step 3: perform statistical Analysis
average_rating = np.mean(ratings)
print(f"Average Customer Rating: {average_rating:.2f}")

Average Customer Rating: 6.00


In [23]:
highest_rating = np.max(ratings)
print(f"Highest Rating Received: {highest_rating}")

lowest_rating = np.min(ratings)
print(f"Lowest Rating Received: {lowest_rating}\n")

Highest Rating Received: 9
Lowest Rating Received: 3



In [24]:
unique_ratings, rating_counts = np.unique(ratings, return_counts=True)

In [25]:
feedback_comments = data[:, 2]

# step 5: display insights
print("\n** customer feedback analysis summary**")
print()

print("**rating distribution:**")
print()
for rating, count in zip(unique_ratings, rating_counts):
    print(f"Rating {rating}: {count} customers")


** customer feedback analysis summary**

**rating distribution:**

Rating 3: 1 customers
Rating 4: 1 customers
Rating 5: 1 customers
Rating 6: 1 customers
Rating 7: 1 customers
Rating 8: 1 customers
Rating 9: 1 customers


In [26]:

# Cese study: policyholder data transformation in insurance industry using numpy


In [27]:
import numpy as np
import pandas as pd

In [10]:
# step 1: create a simple dataset representing insurance policyholder records

# columns: policy number, premium amount(incorrect), insured amount, claim amount (incorrect)

policy_data = np.array([
    [1001, 12000, 500000, 5000],
    [1002, 11000, 530000, 6000],
    [1003, 13000, 520000, 7000],
    [1004, 20000, 510000, 8000],
    [1007, 210000, 540000, 9000],
])

col = ["Policy Number", "Premium Amount", "Insured Amount", "Claim Amount"]
# print original dataset
print("original policyholder data:")
print()
df_before = pd.DataFrame(policy_data, columns = col)
print(df_before)

original policyholder data:

   Policy Number  Premium Amount  Insured Amount  Claim Amount
0           1001           12000          500000          5000
1           1002           11000          530000          6000
2           1003           13000          520000          7000
3           1004           20000          510000          8000
4           1007          210000          540000          9000


In [18]:

policy_data[:, [1, 3]] = policy_data[:, [3, 1]]

print("\ncorrected policyhoder data(after wapping premium and claim amount columns):")
print()
df_after = pd.DataFrame(policy_data, columns = col)
print(df_before)


corrected policyhoder data(after wapping premium and claim amount columns):

   Policy Number  Premium Amount  Insured Amount  Claim Amount
0           1001           12000          500000          5000
1           1002           11000          530000          6000
2           1003           13000          520000          7000
3           1004           20000          510000          8000
4           1007          210000          540000          9000
